import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import MyLayout from "./my/Navbar";
import QueryProvider from "./QueryProvider";
const inter = Inter({ subsets: ["latin"] });
import { Provider } from "./SessionProvider";
import ReduxStoreProvider from "./ReduxStoreProvider";
import { SocketProvider } from "./custom-Hooks/SocketProvider";

export const metadata: Metadata = {
  title: "Pro-Perly",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <QueryProvider>
            <ReduxStoreProvider>
              <StoreProvider>
                <SocketProvider>
                <MyLayout>{children}</MyLayout>
                </SocketProvider>
              </StoreProvider>
            </ReduxStoreProvider>
          </QueryProvider>
        </Provider>
      </body>
    </html>
  );
}
